- name: Create a data container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_container_repo_image }}"
    privileged: "{{ docker_privileged }}"
    exposed_ports: "{{ docker_exposed }}"
    restart: "yes"
    volumes:
      - /docker/data
      - "/opt/nagios/etc:/configs/"
#      - "/opt/nagios/etc/objects/commands.cfg:"
#      - "/opt/nagios/etc/objects/contacts.cfg:"
#      - "/opt/nagios/etc/objects/timeperiods.cfg:"
#      - "/opt/nagios/etc/objects/templates.cfg:"
#      - "/opt/nagios/etc/objects/localhost.cfg:"
#      - "/usr/local/nagios/etc/objects/hosts.cfg:"
#      - "/opt/nagios/etc/objects/windows.cfg:"
#      - "/opt/nagios/etc/objects/switch.cfg:"
#      - "/opt/nagios/etc/objects/printer.cfg:"
#      - "/opt/nagios/etc/servers:"
#      - "/opt/nagios/etc/printers:"
#      - "/opt/nagios/etc/switches:"
#      - "/opt/nagios/etc/routers:"
